apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  clusterIP: None
  ports:
  - name: "portal"
    port: 8080
    targetPort: 80
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
      - name: init-lighthouse
        image: busybox
        command: ['sh', '-c', 'until nslookup lighthouse; do echo Waiting for Lighthouse; sleep 2; done;']
      containers:
      - name: api
        image: cluster.sharding.apinode
        imagePullPolicy: IfNotPresent
        ports:
        - name: api
          containerPort: 80
        - name: akka-remote
          containerPort: 2552
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: CLUSTER_PORT
          value: "2552"
        - name: CLUSTER_SEEDS
          value: akka.tcp://ShopApp@lighthouse:4053
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # resources:
        #   requests:
        #     memory: 110Mi
        #     cpu: "0.017"
        readinessProbe:
          tcpSocket:
            port: 2552
          initialDelaySeconds: 30
          timeoutSeconds: 30
      restartPolicy: Always
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: api
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  # - type: Resource
  #   resource:
  #     name: memory
  #     targetAverageValue: 150Mi