apiVersion: v1
kind: Service
metadata:
  name: lighthouse
  namespace: cluster-sample
  labels:
    app: lighthouse
spec:
  clusterIP: None
  ports:
  - name: "9110"
    port: 9110
    targetPort: 9110
  - name: "4053"
    port: 4053
    targetPort: 4053
  selector:
    app: lighthouse
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lighthouse
  namespace: cluster-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse
  serviceName: lighthouse
  template:
    metadata:
      labels:
        app: lighthouse
    spec:
      containers:
      - name: lighthouse
        image: petabridge/lighthouse:v0.9.2
        env:
        - name: ACTORSYSTEM
          value: ShopApp
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_IP
          value: $(POD_NAME).lighthouse
        - name: CLUSTER_PORT
          value: "4053"
        - name: CLUSTER_SEEDS
          value: akka.tcp://ShopApp@lighthouse-0.lighthouse:4053
        ports:
        - containerPort: 9110
        - containerPort: 4053
        resources:
          limits:
            memory: 512Mi
            cpu: "0.1"
          requests:
            memory: 50Mi
            cpu: "0.02"
      restartPolicy: Always