apiVersion: v1
kind: Service
metadata:
  name: lighthouse
  namespace: cluster-sample
  labels:
    app: lighthouse
spec:
  ports:
  - name: "9110"
    port: 9110
    targetPort: 9110
  - name: "4053"
    port: 4053
    targetPort: 4053
  selector:
    app: lighthouse
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse
  namespace: cluster-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse
  template:
    metadata:
      labels:
        app: lighthouse
    spec:
      containers:
      - name: lighthouse
        image: petabridge/lighthouse:v0.9.2
        env:
        - name: ACTORSYSTEM
          value: webcrawler
        - name: CLUSTER_IP
          value: lighthouse
        - name: CLUSTER_PORT
          value: "4053"
        - name: CLUSTER_SEEDS
          value: akka.tcp://webcrawler@lighthouse:4053
        ports:
        - containerPort: 9110
        - containerPort: 4053
        resources:
          limits:
            memory: 512Mi
            cpu: "0.1"
          requests:
            memory: 50Mi
            cpu: "0.02"
        readinessProbe:
          tcpSocket:
            port: 4053
          initialDelaySeconds: 30
          timeoutSeconds: 30
      restartPolicy: Always
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: lighthouse
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lighthouse
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 50Mi
