apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cluster-sample
  labels:
    app: postgres
spec:
  ports:
  - name: "postgres"
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cluster-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        env:
        - name: POSTGRES_USER
          value: example
        - name: POSTGRES_PASSWORD
          value: example
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: config-volume
          mountPath: /docker-entrypoint-initdb.d
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          timeoutSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: config-postgres
      restartPolicy: Always